server:
  port: 6080

spring:
  application:
    name: spring-boot-demo
  datasource:
    name: default
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot_demo?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    initialize: false
    tomcat:
      validationQuery: 'select 2'
      testOnBorrow: true
      testOnReturn: true
      testWhileIdle: true
      maxWait: 15000
      init-s-q-l: 'set names utf8mb4;'
      maxActive: 5
      maxIdle: 5
      minIdle: 5
      initialSize: 5

mybatis.config-location: classpath:mybatis-config.xml

#logging.config: classpath:log4j2.xml